//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comments
    {
        public int ID { get; set; }
        public int SubjectID { get; set; }
        public int ParentID { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Email { get; set; }
        public string Text { get; set; }
        public string IP { get; set; }
        public System.DateTime Date { get; set; }
        public bool Confirm { get; set; }
        public bool Read { get; set; }
        public int Like { get; set; }
        public int DisLike { get; set; }
    
        public virtual tbl_Subject tbl_Subject { get; set; }
    }
}
