//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RelationshipGroup_Subject
    {
        public int ID { get; set; }
        public int GroupID { get; set; }
        public int SubjectID { get; set; }
    
        public virtual tbl_Grouping tbl_Grouping { get; set; }
        public virtual tbl_Subject tbl_Subject { get; set; }
    }
}
