//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Grouping
    {
        public tbl_Grouping()
        {
            this.tbl_Grouping1 = new HashSet<tbl_Grouping>();
            this.tbl_RelationshipGroup_Subject = new HashSet<tbl_RelationshipGroup_Subject>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int ParentID { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<tbl_Grouping> tbl_Grouping1 { get; set; }
        public virtual tbl_Grouping tbl_Grouping2 { get; set; }
        public virtual ICollection<tbl_RelationshipGroup_Subject> tbl_RelationshipGroup_Subject { get; set; }
    }
}
