//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Subject
    {
        public tbl_Subject()
        {
            this.tbl_Comments = new HashSet<tbl_Comments>();
            this.tbl_RelationshipGroup_Subject = new HashSet<tbl_RelationshipGroup_Subject>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string HeadTitle { get; set; }
        public string Text { get; set; }
        public string FullText { get; set; }
        public string Image { get; set; }
        public string Video { get; set; }
        public string Username { get; set; }
        public long Visit { get; set; }
        public int Like { get; set; }
        public int DisLike { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual ICollection<tbl_Comments> tbl_Comments { get; set; }
        public virtual ICollection<tbl_RelationshipGroup_Subject> tbl_RelationshipGroup_Subject { get; set; }
    }
}
